# Site settings
title: PGOC

email: "ryunx21@gmail.com"
url: "http://ryuncha.github.io"
github_url: "http://github.com/ryuncha/PGOC"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/ryuncha"
baseurl: "/PGOC"
disqus_shortname: https-ryuncha-github-io

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
