# Site settings
title: PGOC

email: "ryunx21@gmail.com"
url: "http://ryuncha.github.io/pgoc/"
github_url: "http://github.com/ryuncha/pgoc/"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/ryuncha"
baseurl: "/pgoc/"
disqus_shortname: ryunchagithub

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
